// @ts-nocheck
import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import { resolveGateway } from '../../utils/gateway-resolver.js';
import fs from 'fs';
import os from 'os';

vi.mock('fs');
vi.mock('os');
vi.mock('../../utils/logger.js', () => ({
  logger: {
    debug: vi.fn(),
    warning: vi.fn(),
    info: vi.fn(),
  },
}));

describe('gateway-resolver', () => {
  let originalPlatform: PropertyDescriptor | undefined;
  let originalEnv: NodeJS.ProcessEnv;

  beforeEach(() => {
    vi.clearAllMocks();
    originalPlatform = Object.getOwnPropertyDescriptor(process, 'platform');
    originalEnv = { ...process.env };
    delete process.env.WSL_DISTRO_NAME;
    delete process.env.WSL_INTEROP;
  });

  afterEach(() => {
    if (originalPlatform) {
      Object.defineProperty(process, 'platform', originalPlatform);
    }
    process.env = originalEnv;
    vi.clearAllMocks();
  });

  describe('resolveGateway()', () => {
    describe('on non-Linux platforms', () => {
      it('returns windows environment on win32', () => {
        Object.defineProperty(process, 'platform', { value: 'win32', configurable: true });

        const result = resolveGateway();

        expect(result.environment).toBe('windows');
        expect(result.gatewayIp).toBeNull();
      });

      it('returns macos environment on darwin', () => {
        Object.defineProperty(process, 'platform', { value: 'darwin', configurable: true });

        const result = resolveGateway();

        expect(result.environment).toBe('macos');
        expect(result.gatewayIp).toBeNull();
      });
    });

    describe('on Linux platform', () => {
      beforeEach(() => {
        Object.defineProperty(process, 'platform', { value: 'linux', configurable: true });
      });

      it('returns wsl2 environment when WSL_DISTRO_NAME is set and /proc/version contains microsoft', () => {
        process.env.WSL_DISTRO_NAME = 'Ubuntu';
        vi.mocked(fs.readFileSync).mockImplementation((path) => {
          if (path === '/proc/version') {
            return 'Linux version 5.15.0-microsoft-standard-WSL2';
          }
          throw new Error('File not found');
        });

        const result = resolveGateway();

        expect(result.environment).toBe('wsl2');
      });

      it('returns wsl1 environment when WSL env is set but /proc/version read fails', () => {
        process.env.WSL_DISTRO_NAME = 'Ubuntu';
        vi.mocked(fs.readFileSync).mockImplementation(() => {
          throw new Error('File not found');
        });

        const result = resolveGateway();

        expect(result.environment).toBe('wsl1');
      });

      it('resolves gateway from /proc/net/route', () => {
        const routeContent = `Iface\tDestination\tGateway\tFlags\tRefCnt\tUse\tMetric\tMask\tMTU\tWindow\tIRTT
eth0\t00000000\t0101A8C0\t0003\t0\t0\t0\t00000000\t0\t0\t0
eth0\t0001A8C0\t00000000\t0001\t0\t0\t0\t00FFFFFF\t0\t0\t0`;

        vi.mocked(fs.readFileSync).mockImplementation((path) => {
          if (path === '/proc/net/route') {
            return routeContent;
          }
          if (path === '/proc/version') {
            return 'Linux version 5.15.0-generic';
          }
          throw new Error('File not found');
        });
        vi.mocked(os.release).mockReturnValue('5.15.0-generic');

        const result = resolveGateway();

        expect(result.environment).toBe('linux');
        expect(result.gatewayIp).toBe('192.168.1.1');
        expect(result.source).toBe('/proc/net/route');
      });

      it('converts hex gateway correctly (little-endian)', () => {
        const routeContent = `Iface\tDestination\tGateway\tFlags\tRefCnt\tUse\tMetric\tMask\tMTU\tWindow\tIRTT
eth0\t00000000\t010011AC\t0003\t0\t0\t0\t00000000\t0\t0\t0`;

        vi.mocked(fs.readFileSync).mockImplementation((path) => {
          if (path === '/proc/net/route') {
            return routeContent;
          }
          if (path === '/proc/version') {
            return 'Linux version 5.15.0-generic';
          }
          throw new Error('File not found');
        });
        vi.mocked(os.release).mockReturnValue('5.15.0-generic');

        const result = resolveGateway();

        expect(result.gatewayIp).toBe('172.17.0.1');
      });

      it('falls back to /etc/resolv.conf for WSL2 when /proc/net/route fails', () => {
        process.env.WSL_DISTRO_NAME = 'Ubuntu';
        const resolvConf = `# This file was automatically generated by WSL.
nameserver 172.25.192.1
search localdomain`;

        vi.mocked(fs.readFileSync).mockImplementation((path) => {
          if (path === '/proc/version') {
            return 'Linux version 5.15.0-microsoft-standard-WSL2';
          }
          if (path === '/etc/resolv.conf') {
            return resolvConf;
          }
          throw new Error('File not found');
        });

        const result = resolveGateway();

        expect(result.environment).toBe('wsl2');
        expect(result.gatewayIp).toBe('172.25.192.1');
        expect(result.source).toBe('/etc/resolv.conf');
      });

      it('returns null gateway when all resolution methods fail', () => {
        process.env.WSL_DISTRO_NAME = 'Ubuntu';
        vi.mocked(fs.readFileSync).mockImplementation((path) => {
          if (path === '/proc/version') {
            return 'Linux version 5.15.0-microsoft-standard-WSL2';
          }
          throw new Error('File not found');
        });

        const result = resolveGateway();

        expect(result.environment).toBe('wsl2');
        expect(result.gatewayIp).toBeNull();
      });

      it('skips invalid gateway IPs in /proc/net/route', () => {
        const routeContent = `Iface\tDestination\tGateway\tFlags\tRefCnt\tUse\tMetric\tMask\tMTU\tWindow\tIRTT
eth0\t00000000\tZZZZZZZZ\t0003\t0\t0\t0\t00000000\t0\t0\t0`;

        vi.mocked(fs.readFileSync).mockImplementation((path) => {
          if (path === '/proc/net/route') {
            return routeContent;
          }
          if (path === '/proc/version') {
            return 'Linux version 5.15.0-generic';
          }
          throw new Error('File not found');
        });
        vi.mocked(os.release).mockReturnValue('5.15.0-generic');

        const result = resolveGateway();

        expect(result.gatewayIp).toBeNull();
      });

      it('uses os.release() fallback for WSL detection', () => {
        vi.mocked(fs.readFileSync).mockImplementation(() => {
          throw new Error('File not found');
        });
        vi.mocked(os.release).mockReturnValue('5.10.16.3-microsoft-standard-WSL2');

        const result = resolveGateway();

        expect(result.environment).toBe('wsl2');
      });

    });
  });
});
