// proxy/state.mjs — the proxy's single mutable state object (extracted from
// godot-mcp-proxy.mjs module-level lets/const-collections, SEE-1334 Phase 0a).
// Every module mutates through S so the split stays behavior-identical to the
// monolith (one shared heap of state, same init values). Const collections
// (Maps/Sets/arrays) live here too: uniform S.x access, same identity.
import { STAGE_ENUM } from '../warmup-stage-parser.mjs';

export const S = {
    startedAt: Date.now(),
    warm: false,
    warmupTimedOut: false, // terminal FAILED_EXIT only (set at T4, just before exit)
    recovering: false,
    recoveringEnteredAt: 0,
    recoveringCliUnconnectedSince: 0,
    pendingCalls: [],
    lastProgressAt: 0,
    renderStable: false,
    npx: null,
    npxRunning: false,
    shutdownRequested: false,
    warmupTimeoutMs: null,
    coldNpxRestarts: 0,
    hotNpxRestarts: 0,
    warmAt: 0,
    npxStdinReady: false,
    npxWriteBuffer: [],
    pendingHandshake: new Map(),
    screenshotCallIds: new Set(),
    screenshotContract: new Map(),
    uiInspectCallIds: new Set(),
    execCallIds: new Set(),
    toolsCallIds: new Set(),
    toolsCallLines: new Map(),
    spawnTriggered: false,
    spawnInFlight: null,
    spawnAttempts: 0,
    spawnFailedBucket: null,
    spawnFailedStreak: 0,
    spawnBackoffUntil: 0,
    forceRestartCount: 0,
    spawnStartedAt: 0,
    spawnTerminal: false,
    giveUpCount: 0,
    giveUpArmedAt: 0,
    giveUpBackoffMs: 0,
    giveUpLastReason: '',
    graceRaceGuardFired: false,
    graceRaceRespawn: false,
    firstProbeOkAt: 0,
    spawnLastFailed: false,
    spawnLastError: null,
    lastSpawnReused: false,
    firstCallProgressToken: null,
    stage: 'LAUNCHER_EXEC',
    stageTimestamps: {},
    tcpReceivedCount: 0,
    logTailAvailable: false,
    logTailUnavailableSince: 0,
    leaseExitDetected: false,
    warmupJustCompleted: false,
    coldMode: false,
    warmEditorDead: false,
    warmRespawnInFlight: false,
    restartHold: null,
    npxTransportReady: false,
    npxCliConnected: false,
    npxReadyDropped: false,
    lastMutationAtMs: 0,
    lastFrameAdvanceAtMs: 0,
    internalExecWaiters: new Map(),
    internalExecTimers: new Map(),
    pendingAutoStepCalls: new Map(),
    toolsCacheRefreshInFlight: false,
    toolsCacheRefreshedForSpawn: false,
    toolsCacheWaiters: new Map(),
    takeoverFailStreak: 0,
    takeoverSelfHealInFlight: false,
    staleTakeoverInFlight: false,
    staleProxyTakeovers: 0,
    takeover: null,
    renderStableTimer: null,
    leaseTimer: null,
    leaseOffset: 0,
    hasPrunedBareRepo: false,
    lastBareRepoPruneDiag: null,
    stageNotified: '',
    resolvedGodotMcpCmd: null,
    lastRegistryRefreshMs: 0,
    lastEditorPidBackfillMs: 0,   // SEE-1348 WP4: heartbeat editor_pid backfill throttle
    proxyPidRegistered: false,
    warmProbeFailures: 0,
    recoveryRound: 0,
    recoveryWindowStart: null,
};
for (const s of STAGE_ENUM) S.stageTimestamps[s] = null;
S.stageTimestamps.LAUNCHER_EXEC = S.startedAt; // t0 = proxy start (per §2.1)
